FROM node:16

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV}

ARG REACT_APP_DSN_URL
ENV REACT_APP_DSN_URL=${REACT_APP_DSN_URL}

ARG REACT_APP_FIREBASE_API_KEY
ENV REACT_APP_FIREBASE_API_KEY=${REACT_APP_FIREBASE_API_KEY}

ARG REACT_APP_FIREBASE_AUTH_DOMAIN
ENV REACT_APP_FIREBASE_AUTH_DOMAIN=${REACT_APP_FIREBASE_AUTH_DOMAIN}

ARG REACT_APP_FIREBASE_MESSAGING_SENDER_ID
ENV REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${REACT_APP_FIREBASE_MESSAGING_SENDER_ID}

ARG REACT_APP_FIREBASE_PROJECT_ID
ENV REACT_APP_FIREBASE_PROJECT_ID=${REACT_APP_FIREBASE_PROJECT_ID}

ARG REACT_APP_FIREBASE_STORAGE_BUCKET
ENV REACT_APP_FIREBASE_STORAGE_BUCKET=${REACT_APP_FIREBASE_STORAGE_BUCKET}

ARG REACT_APP_MESSAGING_SENDER_ID
ENV REACT_APP_MESSAGING_SENDER_ID=${REACT_APP_MESSAGING_SENDER_ID}


COPY package.json ./
COPY yarn.lock ./

RUN yarn --silent

COPY . ./

RUN yarn build

CMD ["yarn", "start"]