name: Push to Nexus

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set insecure registry
        run: |
          echo "{ \"insecure-registries\": [\"lo-nexus.apps.lo.agency:8880\"] }" | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            lo-nexus.apps.lo.agency:8880/lo-agency/polaris
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=sha
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          config-inline: |
            [registry."lo-nexus.apps.lo.agency:8880"]
              http = true
              insecure = true
      -
        name: Login to Nexus Container Registry
        uses: docker/login-action@v1 
        with:
          registry: lo-nexus.apps.lo.agency:8880
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          REACT_APP_DSN_URL: ${{ secrets.REACT_APP_DSN_URL }}
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
          REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
